apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp-gh-240730
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp-gh-240730 
  name: goapp-gh-240730
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: goapp-gh-240730
    weight: 100 
